const contractSelectionReceivable = [
  "ReceivableContract.id",
  "ReceivableContract.parentId",
  "ReceivableContract.contractCode",
  "ReceivableContract.bancaryInfo.accountNumber",
  "ReceivableContract.bancaryInfo.agency",
  "ReceivableContract.bancaryInfo.dv",
  "ReceivableContract.bancaryInfo.bank",
  "ReceivableContract.pixInfo.key",
  "ReceivableContract.pixInfo.key_type",
  "ReceivableContract.object",
  "ReceivableContract.createdAt",
  "ReceivableContract.contractPeriod.start",
  "ReceivableContract.contractPeriod.end",
  "ReceivableContract.totalValue",
  "ReceivableContract.agreement",
  "ReceivableContractBudgetPlan.id",
  "ReceivableContractBudgetPlan.scenarioName",
  "ReceivableContractBudgetPlan.year",
  "ReceivableContractBudgetPlan.version",
  "ReceivableContractFinancier.id",
  "ReceivableContractFinancier.cnpj",
  "ReceivableContractFinancier.name",
  "ReceivableContractFinancier.address",
  "ReceivableContractFinancier.telephone",
];

const defaultFinancierContractFields = [
  "FinancierContracts.id",
  "FinancierContracts.bancaryInfo.bank",
  "FinancierContracts.bancaryInfo.agency",
  "FinancierContracts.bancaryInfo.dv",
  "FinancierContracts.bancaryInfo.accountNumber",
  "FinancierContracts.pixInfo.key_type",
  "FinancierContracts.pixInfo.key",
  "FinancierContracts.contractCode",
  "FinancierContracts.budgetPlan",
  "FinancierContracts.collaborator",
  "FinancierContracts.financier",
  "FinancierContracts.createdAt",
  "FinancierContracts.contractStatus",
  "FinancierContracts.object",
  "FinancierContracts.contractPeriod.start",
  "FinancierContracts.contractPeriod.end",
  "FinancierContracts.supplier",
  "FinancierContracts.totalValue",
  "FinancierContracts.agreement",
  "FinancierContracts.parentId",
  "FinancierContractsP.id",
  "FinancierContractsR.id",
];

export const defaultSelectColumnsReceivable = [
  "Receivable.id",
  "Receivable.identifierCode",
  "Financier.id",
  "Financier.cnpj",
  "Financier.name",
  "Financier.corporateName",
  "Financier.address",
  "Financier.telephone",
  "Receivable.financierId",
  "Receivable.receivableStatus",
  "Receivable.description",
  "Receivable.receivableType",
  "Receivable.totalValue",
  "Receivable.receiptMethod",
  "Receivable.docType",
  "Receivable.accountId",
  "Receivable.recurrent",
  "Receivable.recurenceData.recurrenceType",
  "Receivable.recurenceData.startDate",
  "Receivable.recurenceData.endDate",
  "Receivable.recurenceData.dueDay",
  "Categorization.budgetPlanId",
  "Categorization.programId",
  "Categorization.costCenterId",
  "Categorization.categoryId",
  "Categorization.subCategoryId",
  "Receivable.dueDate",
  "BudgetPlan.year",
  "BudgetPlan.scenarioName",
  "BudgetPlan.version",
  "CostCenter.name",
  "CostCenterCategory.name",
  "CostCenterSubCategory.name",
  "Files.id",
  "Files.fileUrl",
  "Installments.id",
  "Installments.installmentNumber",
  "Installments.dueDate",
  "Installments.type",
  "Installments.value",
  "Installments.status",
  "Installments.receivableId",
  "Installments.totalInstallments",
  "Installments.relatedLiquidInstallmentId",
  "Receivable.createdAt",
  "Receivable.updatedAt",
  "Program.id",
  "Program.name",
]
  .concat(contractSelectionReceivable)
  .concat(defaultFinancierContractFields);

export const defaultSelectQueryColumnsReceivable = [
  "Receivable.id",
  "Receivable.identifierCode",
  "Receivable.receivableType",
  "Receivable.contract",
  "Receivable.totalValue",
  "Receivable.receiptMethod",
  "Receivable.receivableStatus",
  "Receivable.docType",
  "Receivable.account",
  "Receivable.description",
  "Receivable.recurrent",
  "Receivable.recurenceData.recurrenceType",
  "Receivable.recurenceData.startDate",
  "Receivable.recurenceData.endDate",
  "Receivable.recurenceData.dueDay",
  "Receivable.dueDate",
  "Financier.id",
  "Financier.name",
  "Financier.cnpj",
  "Program.id",
  "Program.name",
  "Program.abbreviation",
  "Program.active",
  "BudgetPlan.id",
  "BudgetPlan.year",
  "BudgetPlan.scenarioName",
  "BudgetPlan.version",
  "CostCenter.id",
  "CostCenter.name",
  "CostCenter.active",
  "CostCenterCategory.id",
  "CostCenterCategory.name",
  "CostCenterCategory.active",
  "CostCenterSubCategory.id",
  "CostCenterSubCategory.name",
  "CostCenterSubCategory.type",
  "File.id",
  "File.fileUrl",
];

export const defaultListReceivablesSelect = [
  "Receivable.id",
  "Receivable.createdAt",
  "Receivable.description",
  "Receivable.receivableType",
  "Receivable.contract",
  "Receivable.totalValue",
  "Receivable.receivableStatus",
  "Financier.id",
  "Financier.name",
  "CostCenter.id",
  "CostCenter.name",
  "CostCenterCategory.id",
  "CostCenterCategory.name",
  "CostCenterSubCategory.id",
  "CostCenterSubCategory.name",
  "Installments.id",
  "Installments.status",
];

export const queryFields = {
  budgetPlanId: "BudgetPlan.id",
  dueBetween: "Receivable.dueDate",
  valueBetween: "Receivable.totalValue",
  receivableType: "Receivable.receivableType",
  accountId: "Receivable.accountId",
  receivableStatus: "Receivable.receivableStatus",
  costCenterId: "CostCenter.id",
  categoryId: "CostCenterCategory.id",
  subCategoryId: "CostCenterSubCategory.id",
};

export const PDFHeaders = [
  "CODIGO",
  "FINANCIADOR",
  "STATUS",
  "TIPO",
  "TOTAL",
  "METODO RECEBIMENTO",
  "CONTA",
  "CONTRATO",
  "RECORRENTE",
  "TIPO RECO",
  "INICIO RECO",
  "FIM RECO",
  "DIA",
  "VENCIMENTO",
  "PROGRAMA",
  "PLANO ORÇAMENTÁRIO",
  "CENTRO DE CUSTO",
  "CATEGORIA",
  "SUBCATEGORIA",
];
