const contractSelectionPayables = [
  "Contract.id",
  "Contract.parentId",
  "Contract.contractCode",
  "Contract.bancaryInfo.accountNumber",
  "Contract.bancaryInfo.agency",
  "Contract.bancaryInfo.dv",
  "Contract.bancaryInfo.bank",
  "Contract.pixInfo.key",
  "Contract.pixInfo.key_type",
  "Contract.object",
  "Contract.createdAt",
  "Contract.contractPeriod.start",
  "Contract.contractPeriod.end",
  "Contract.totalValue",
  "Contract.agreement",
  "ContractBudgetPlan.id",
  "ContractBudgetPlan.scenarioName",
  "ContractBudgetPlan.year",
  "ContractBudgetPlan.version",
  "ContractProgram.id",
  "ContractProgram.name",
];

const defaultSupplierContractFields = [
  "SupplierContracts.id",
  "SupplierContracts.bancaryInfo.bank",
  "SupplierContracts.bancaryInfo.agency",
  "SupplierContracts.bancaryInfo.dv",
  "SupplierContracts.bancaryInfo.accountNumber",
  "SupplierContracts.pixInfo.key_type",
  "SupplierContracts.pixInfo.key",
  "SupplierContracts.contractCode",
  "SupplierContracts.budgetPlan",
  "SupplierContracts.collaborator",
  "SupplierContracts.financier",
  "SupplierContracts.createdAt",
  "SupplierContracts.contractStatus",
  "SupplierContracts.object",
  "SupplierContracts.contractPeriod.start",
  "SupplierContracts.contractPeriod.end",
  "SupplierContracts.supplier",
  "SupplierContracts.totalValue",
  "SupplierContracts.agreement",
  "SupplierContracts.parentId",
  "SupplierContractsP.id",
  "SupplierContractsR.id",
];

const defaultCollaboratorContractFields = [
  "CollaboratorContracts.id",
  "CollaboratorContracts.bancaryInfo.bank",
  "CollaboratorContracts.bancaryInfo.agency",
  "CollaboratorContracts.bancaryInfo.dv",
  "CollaboratorContracts.bancaryInfo.accountNumber",
  "CollaboratorContracts.pixInfo.key_type",
  "CollaboratorContracts.pixInfo.key",
  "CollaboratorContracts.contractCode",
  "CollaboratorContracts.budgetPlan",
  "CollaboratorContracts.collaborator",
  "CollaboratorContracts.financier",
  "CollaboratorContracts.createdAt",
  "CollaboratorContracts.contractStatus",
  "CollaboratorContracts.object",
  "CollaboratorContracts.contractPeriod.start",
  "CollaboratorContracts.contractPeriod.end",
  "CollaboratorContracts.supplier",
  "CollaboratorContracts.totalValue",
  "CollaboratorContracts.agreement",
  "CollaboratorContracts.parentId",
  "CollaboratorContractsP.id",
  "CollaboratorContractsR.id",
];

export const defaultSelectColumnsPayables = [
  "Payable.id",
  "Payable.identifierCode",
  "Payable.accountId",
  "Payable.supplierId",
  "Payable.collaboratorId",
  "Payable.payableStatus",
  "Payable.obs",
  "Payable.paymentType",
  "Payable.debtorType",
  "Payable.totalValue",
  "Payable.liquidValue",
  "Payable.taxValue",
  "Payable.paymentMethod",
  "Payable.docType",
  "Payable.account",
  "Payable.recurrent",
  "Payable.dueDate",
  "Payable.competenceDate",
  "Payable.paymentDate",
  "Payable.createdById",
  "Payable.updatedById",
  "Payable.createdAt",
  "Payable.updatedAt",
  "Payable.contractId",
  "Categorization.costCenterId",
  "Categorization.categoryId",
  "Categorization.subCategoryId",
  "Categorization.programId",
  "Categorization.budgetPlanId",
  "Supplier.id",
  "Supplier.cnpj",
  "Supplier.name",
  "Supplier.fantasyName",
  "Supplier.serviceCategory",
  "Supplier.bancaryInfo.accountNumber",
  "Supplier.bancaryInfo.agency",
  "Supplier.bancaryInfo.dv",
  "Supplier.bancaryInfo.bank",
  "Supplier.pixInfo.key",
  "Supplier.pixInfo.key_type",
  "Payable.recurenceData.recurrenceType",
  "Payable.recurenceData.startDate",
  "Payable.recurenceData.endDate",
  "Payable.recurenceData.dueDay",
  "Files.id",
  "Files.fileUrl",
  "BudgetPlan.id",
  "BudgetPlan.year",
  "BudgetPlan.scenarioName",
  "BudgetPlan.version",
  "Approvals.id",
  "Approvals.approved",
  "Approvals.obs",
  "ApprovalsCollaborators.id",
  "ApprovalsCollaborators.name",
  "ApprovalsCollaborators.email",
  "ApprovalsUser.id",
  "ApprovalsUser.name",
  "ApprovalsUser.email",
  "Collaborator.id",
  "Collaborator.name",
  "Collaborator.cpf",
  "Collaborator.email",
  "Collaborator.role",
  "Installment.id",
  "Installment.installmentNumber",
  "Installment.dueDate",
  "Installment.type",
  "Installment.value",
  "Installment.status",
  "Installment.payableId",
  "Installment.totalInstallments",
  "Installment.relatedLiquidInstallmentId",
  "CostCenter.id",
  "CostCenter.name",
  "CostCenterCategory.id",
  "CostCenterCategory.name",
  "CostCenterSubCategory.id",
  "CostCenterSubCategory.name",
  "Program.name",
  "Program.id",
]
  .concat(contractSelectionPayables)
  .concat(defaultSupplierContractFields)
  .concat(defaultCollaboratorContractFields);

export const defaultSelectColumnsExportCnabPayables = [
  "Payables.id",
  "Payables.identifierCode",
  "Payables.supplierId",
  "Payables.payableStatus",
  "Payables.obs",
  "Payables.paymentType",
  "Payables.totalValue",
  "Payables.debtorType",
  "Payables.liquidValue",
  "Payables.taxValue",
  "Payables.paymentMethod",
  "Payables.barcode",
  "Payables.docType",
  "Payables.account",
  "Payables.recurrent",
  "Payables.dueDate",
  "Payables.competenceDate",
  "Payables.paymentDate",
  "Payables.createdById",
  "Payables.updatedById",
  "Payables.createdAt",
  "Payables.updatedAt",
  "Account.id",
  "Account.bank",
  "Account.agency",
  "Account.accountNumber",
  "Account.dv",
  "Supplier.id",
  "Supplier.cnpj",
  "Supplier.name",
  "Supplier.fantasyName",
  "Supplier.serviceCategory",
  "Supplier.bancaryInfo.accountNumber",
  "Supplier.bancaryInfo.agency",
  "Supplier.bancaryInfo.dv",
  "Supplier.bancaryInfo.bank",
  "Supplier.pixInfo.key",
  "Supplier.pixInfo.key_type",
  "Payables.recurenceData.recurrenceType",
  "Payables.recurenceData.startDate",
  "Payables.recurenceData.endDate",
  "Payables.recurenceData.dueDay",
  "Collaborator.id",
  "Collaborator.name",
  "Collaborator.cpf",
  "Collaborator.email",
  "Collaborator.role",
  "Installments.id",
  "Installments.installmentNumber",
  "Installments.dueDate",
  "Installments.type",
  "Installments.value",
  "Installments.status",
];

export const defaultSelectQueryColumnsPayables = [
  "Payable.id",
  "Payable.createdAt",
  "Payable.updatedAt",
  "Payable.obs",
  "Payable.totalValue",
  "Payable.identifierCode",
  "Payable.paymentType",
  "Payable.contract",
  "Payable.liquidValue",
  "Payable.taxValue",
  "Payable.paymentMethod",
  "Payable.payableStatus",
  "Payable.docType",
  "Payable.account",
  "Payable.recurrent",
  "Payable.recurenceData.recurrenceType",
  "Payable.recurenceData.startDate",
  "Payable.recurenceData.endDate",
  "Payable.recurenceData.dueDay",
  "Payable.dueDate",
  "Payable.competenceDate",
  "Payable.paymentDate",
  "Supplier.id",
  "Supplier.name",
  "Supplier.cnpj",
  "Program.id",
  "Program.name",
  "Program.abbreviation",
  "Program.active",
  "BudgetPlan.id",
  "BudgetPlan.year",
  "BudgetPlan.scenarioName",
  "BudgetPlan.version",
  "CostCenter.id",
  "CostCenter.name",
  "CostCenter.active",
  "CostCenterCategory.id",
  "CostCenterCategory.name",
  "CostCenterCategory.active",
  "CostCenterSubCategory.id",
  "CostCenterSubCategory.name",
  "CostCenterSubCategory.type",
  "File.id",
  "File.fileUrl",
];

export const defaultListPayablesSelect = [
  "Payable.id",
  "Payable.createdAt",
  "Payable.updatedAt",
  "Payable.obs",
  "Payable.paymentType",
  "Payable.debtorType",
  "Payable.totalValue",
  "Payable.payableStatus",
  "Payable.dueDate",
  "Payable.competenceDate",
  "Payable.paymentDate",
  "Supplier.id",
  "Supplier.name",
  "Categorization",
  "CostCenter.id",
  "CostCenter.name",
  "CostCenterCategory.id",
  "CostCenterCategory.name",
  "CostCenterSubCategory.id",
  "CostCenterSubCategory.name",
  "Collaborator.id",
  "Collaborator.name",
  "Contract.id",
  "Contract.contractCode",
  "Approvals.id",
  "Installment.id",
  "Installment.status",
  "Installment.type",
];

export const queryFields = {
  budgetPlanId: "BudgetPlan.id",
  dueBetween: "Installment.dueDate",
  valueBetween: "Payable.totalValue",
  paymentType: "Payable.paymentType",
  account: "Payable.account",
  payableStatus: "Payable.payableStatus",
  costCenterId: "CostCenter.id",
  categoryId: "CostCenterCategory.id",
  subCategoryId: "CostCenterSubCategory.id",
  approver: "Approvals.collaboratorId",
};

export const PDFHeaders = [
  "CODIGO",
  "FORNECEDOR",
  "STATUS",
  "VALOR TOTAL",
  "METODO DE PAGAMENTO",
  "CONTA",
  "CONTRATO",
  "RECORRENTE",
  "TIPO RECORRENCIA",
  "INICIO RECORRENCIA",
  "FIM RECORRENCIA",
  "DIA RECORRENCIA",
  "DATA VENCIMENTO",
  "COMPETENCIA",
  "PROGRAMA",
  "PLANO ORÇAMENTÁRIO",
  "CENTRO DE CUSTO",
  "CATEGORIA",
  "SUBCATEGORIA",
];

export const CONFIG_ABC = {
  empresa_num_insc: process.env.EMPRESA_NUM_INSC || '',
  convenio: process.env.CONVENIO || '',
  nome_banco: process.env.NOME_BANCO || 'BANCO BRADESCO S.A.',
}